name: triggered-by-workflow
on:
  push:
    branches:
      - '*'
  workflow_trigger: 
  schedule:
    - cron: "*/10 * * * *"
jobs:
  triggered_by:
    runs-on: ubuntu-latest
    steps:
      - name: display_trigger
        run: echo "Le job a été déclenché par un événement de type ${{ github.event_name }}"
