name: checkout-workflow
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Afficher le contenu de README.md
        run: cat README.md