name: execute-script-workflow-3.5
on: [push]
jobs:
  execute_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Exécuter le script demo.py
        run: python demo.py