name: workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
        default: 'john.doe'
      level:
        description: 'Level'
        required: true
        default: 'intermediate'
      class:
        description: 'Class'
        required: true
        default: 'Niveau 3'
        options:
          - 'Niveau 1'
          - 'Niveau 2'
          - 'Niveau 3'
jobs:
  workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: player_infos
        run: |
          echo "Le joueur + ${{ github.event.inputs.username }} + est de niveau + ${{ github.event.inputs.level }} + et joue un + ${{ github.event.inputs.class }}"